import { type NextPage } from "next";

import * as grpc from "@grpc/grpc-js";
import Head from "next/head";
import Link from "next/link";


import { api } from "@/utils/api";
import { GreeterClient } from "@/proto/helloworld_grpc_pb";
import { HelloRequest } from "@/proto/helloworld_pb";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // const [val, setVal] = useState("")

  // useEffect(() => {
  //   const req = new HelloRequest()
  //   req.setName("Beer")
  //   greeterClient.sayHello(req, (e, res) => {
  //     setVal(res.getMessage())
  //     console.log(res)
  //     console.log(e)
  //   })
  // }, [])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;


export async function getServerSideProps() {
  const greeterClient = new GreeterClient('127.0.0.1:50051', grpc.credentials.createInsecure());
    const req = new HelloRequest()
    req.setName("Beer")
    greeterClient.sayHello(req, (e, res) => {
      console.log(res)
      console.log(res.getMessage())
      console.log(e)
    })
    // console.log("test")
  return {
    props: {
      data: "hi"
    }, // will be passed to the page component as props
  }
}